// <auto-generated />
namespace Clone_MovieMVC_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_attributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_attributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201912292235564_add_attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
